FROM python:3.6.5-stretch
LABEL maintainer="a.guillermo.guzman@gmail.com"

ENV DEBIAN_FRONTEND noninteractive

WORKDIR /usr/src/app

# Install requirements for application runtime
COPY requirements.txt ./
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Install node, npm, nodemon - nodemon watches app directory
RUN apt-get update -y && \
    apt-get install -y curl vim && \
    curl -sL https://deb.nodesource.com/setup_9.x | bash && \
    apt-get install -y nodejs && \
    which node && \
    which npm && \
    npm install --global nodemon

# Expose sanic server port
EXPOSE 8000:8000
CMD [ "python", "./src/app.py" ]
