FROM python:3.6.5-stretch
LABEL maintainer="a.guillermo.guzman@gmail.com"

ENV DEBIAN_FRONTEND noninteractive

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

#RUN apk update && apk add nodejs && npm i -g nodemon

EXPOSE 8000:8000

RUN apt-get update -y && \
    apt-get install -y curl vim && \
    curl -sL https://deb.nodesource.com/setup_9.x | bash && \
    apt-get install -y nodejs && \
    which node && \
    which npm && \
    npm install --global nodemon

CMD [ "python", "./app.py" ]
