version: "3"
services:
  app:
    build:
      dockerfile: Dockerfile-python
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: bash -c "python app.py"
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    build:
      dockerfile: Dockerfile-mongo
      context: .
    expose:
      - "27017"
    command: mongod
