FROM python:3.6.5-stretch
LABEL maintainer="a.guillermo.guzman@gmail.com"

ENV DEBIAN_FRONTEND noninteractive

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000:8000

CMD [ "python", "./app.py" ]
