version: "3.6"
services:

  app:
    build:
      dockerfile: Dockerfile-dev
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: >
      nodemon --watch /usr/src/app/src --exec python src/app.py
    links:
      - mongodb
    depends_on:
      - mongodb
    volumes:
      - "./:/usr/src/app"

  mongodb:
    build:
      dockerfile: Dockerfile-mongo
      context: .
    expose:
      - "27017"
    command: mongod
